[package]
name = "substrate-color-gen"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bigcolor = "1.2.1"
clap = { version = "4.5.49", features = ["derive"] }
itertools = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tera = "1.20.0"
