name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Copy Binaries
        run: |
          mkdir -p artifacts
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/release/substrate-color-gen.exe artifacts/substrate-color-gen-windows.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp target/release/substrate-color-gen artifacts/substrate-color-gen-macos
          else
            # assume linux for ubuntu-latest
            cp target/release/substrate-color-gen artifacts/substrate-color-gen-linux
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: substrate-color-gen-${{ matrix.os }}
          path: artifacts/
  
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*/substrate-color-gen*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}